name: Trigger auto deployment for album-api

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'src/**'
    - '.github/workflows/album-api-AutoDeployTrigger-35cfd739-90b4-4045-87ca-651346ee505a.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: cabf2505c0a8acr.azurecr.io
          username: ${{ secrets.ALBUMAPI_REGISTRY_USERNAME }}
          password: ${{ secrets.ALBUMAPI_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: cabf2505c0a8acr.azurecr.io/album-api:${{ github.sha }}
          file: ./src/Dockerfile
          context: ./src/


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.ALBUMAPI_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n album-api -g album-containerapps --server cabf2505c0a8acr.azurecr.io --username  ${{ secrets.ALBUMAPI_REGISTRY_USERNAME }} --password ${{ secrets.ALBUMAPI_REGISTRY_PASSWORD }}
            az containerapp update -n album-api -g album-containerapps --image cabf2505c0a8acr.azurecr.io/album-api:${{ github.sha }}
